name: Deploy Azure Resource Group

on:
  workflow_dispatch:   # permite rodar manualmente no GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login no Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Criar Resource Group
        run: |
          az group create \
            --name MeuResourceGroupTest \
            --location eastus
