name: Deploy Azure Windows VM

on:
  workflow_dispatch:

jobs:
  deploy-windows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login no Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Dar permissão de execução no script
        run: chmod +x scripts/create-vm-windowsrv.sh

      - name: Criar VM Windows
        env:
          ADMIN_PASSWORD: ${{ secrets.VM_WIN_PASSWORD }}
        run: |
          export ADMIN_PASSWORD="${ADMIN_PASSWORD}"
          ./scripts/create-vm-windowsrv.sh
