name: Deploy Azure Resource Group

on:
  workflow_dispatch:   # permite rodar manualmente no GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login no Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Dar permissão de execução no script
        run: chmod +x scripts/create-rg.sh
        
      - name: Rodar Script create-rg.sh
        run: ./scripts/create-rg.sh
