name: Deploy Azure VM Linux

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login no Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Dar permissão de execução no script
        run: chmod +x scripts/create-vm-srv.sh
        
      - name: Executar script de criação
        run: ./scripts/create-vm-srv.sh
